# __author__ = 'trananhdung'
# Docker version 18.06.1-ce, build e68fc7a

version: '3'
services:
  postgres_10:
    image: postgres:10
    ports:
      - 5433:5432
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    restart: always
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_DB=odoo
      - PGDATA=/var/lib/postgresql/data
    networks:
      - default

  odoo_12:
    build: ./odoo_docker/odoo
#    image: trananhdung17/debian-odoo:12.0
    volumes:
      - ./requirements.txt:/requirements.txt
      - ./addons:/addons
      - ./extra_addons:/extra_addons
      - ./odoo-server.log:/odoo/odoo-server.log
      - ./odoo-server.conf:/odoo/odoo-server.conf
      - /tmp:/tmp
    links:
      - "postgres_10:postgres_10"
    environment:
      - DB_HOST=postgres_10
    restart: always
    depends_on:
      - "postgres_10"
    networks:
      - default

  nginx:
    build: ./odoo_docker/nginx
    ports:
      - 8069:8069
    links:
      - "odoo_12:odoo_12"
    environment:
      - ODOO_SERVER=odoo_12
    networks:
      - default
    depends_on:
      - odoo_12

networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450
