# __author__ = 'trananhdung'
# Docker version 18.06.1-ce, build e68fc7a

FROM trananhdung17/debian-odoo:12.0

# COPY ./entrypoint.sh /entrypoint.sh

# ENTRYPOINT "/entrypoint.sh"

USER odoo
CMD 'python3' '/odoo/odoo-bin' '--config=/odoo/odoo-server.conf'
